Traceback (most recent call last):
  File "C:\Users\cxcs\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\cxcs\Anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\cxcs\Anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\cxcs\Anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\cxcs\Anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\cxcs\Anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\Users\cxcs\Anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\cxcs\Anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
c = cdsapi.Client(url=URL, key=KEY)
c.retrieve(
    'reanalysis-uerra-europe-single-levels',
    {
        'origin': 'uerra_harmonie',
        'variable': '10m_wind_speed',
        'year': [
            '1989', '1990', '1991',
            '1992', '1993', '1994',
            '1995', '1996', '1997',
            '1998', '1999', '2000',
            '2001', '2002', '2003',
            '2004', '2005', '2006',
            '2007', '2008', '2009',
            '2010', '2011', '2012',
            '2013', '2014', '2015',
            '2016', '2017', '2018',
        ],
        'month': '01',
        'day': '15',
        'time': '06:00',
        'format': 'netcdf',
    },
    f'{DATADIR}UERRA_ws10m.nc')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_16336/4198867487.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [0mc[0m [1;33m=[0m [0mcdsapi[0m[1;33m.[0m[0mClient[0m[1;33m([0m[0murl[0m[1;33m=[0m[0mURL[0m[1;33m,[0m [0mkey[0m[1;33m=[0m[0mKEY[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m c.retrieve(
[0m[0;32m      3[0m     [1;34m'reanalysis-uerra-europe-single-levels'[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m     {
[0;32m      5[0m         [1;34m'origin'[0m[1;33m:[0m [1;34m'uerra_harmonie'[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\cdsapi\api.py[0m in [0;36mretrieve[1;34m(self, name, request, target)[0m
[0;32m    346[0m [1;33m[0m[0m
[0;32m    347[0m     [1;32mdef[0m [0mretrieve[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mname[0m[1;33m,[0m [0mrequest[0m[1;33m,[0m [0mtarget[0m[1;33m=[0m[1;32mNone[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 348[1;33m         [0mresult[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_api[0m[1;33m([0m[1;34m"%s/resources/%s"[0m [1;33m%[0m [1;33m([0m[0mself[0m[1;33m.[0m[0murl[0m[1;33m,[0m [0mname[0m[1;33m)[0m[1;33m,[0m [0mrequest[0m[1;33m,[0m [1;34m"POST"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    349[0m         [1;32mif[0m [0mtarget[0m [1;32mis[0m [1;32mnot[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    350[0m             [0mresult[0m[1;33m.[0m[0mdownload[0m[1;33m([0m[0mtarget[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\cdsapi\api.py[0m in [0;36m_api[1;34m(self, url, request, method)[0m
[0;32m    415[0m             [0maction[0m [1;33m=[0m [0msession[0m[1;33m.[0m[0mpost[0m[1;33m[0m[1;33m[0m[0m
[0;32m    416[0m [1;33m[0m[0m
[1;32m--> 417[1;33m         result = self.robust(action)(
[0m[0;32m    418[0m             [0murl[0m[1;33m,[0m [0mjson[0m[1;33m=[0m[0mrequest[0m[1;33m,[0m [0mverify[0m[1;33m=[0m[0mself[0m[1;33m.[0m[0mverify[0m[1;33m,[0m [0mtimeout[0m[1;33m=[0m[0mself[0m[1;33m.[0m[0mtimeout[0m[1;33m[0m[1;33m[0m[0m
[0;32m    419[0m         )

[1;32m~\Anaconda3\lib\site-packages\cdsapi\api.py[0m in [0;36mwrapped[1;34m(*args, **kwargs)[0m
[0;32m    604[0m             [1;32mwhile[0m [0mtries[0m [1;33m<[0m [0mself[0m[1;33m.[0m[0mretry_max[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    605[0m                 [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 606[1;33m                     [0mr[0m [1;33m=[0m [0mcall[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    607[0m                 except (
[0;32m    608[0m                     [0mrequests[0m[1;33m.[0m[0mexceptions[0m[1;33m.[0m[0mConnectionError[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\requests\sessions.py[0m in [0;36mpost[1;34m(self, url, data, json, **kwargs)[0m
[0;32m    588[0m         """
[0;32m    589[0m [1;33m[0m[0m
[1;32m--> 590[1;33m         [1;32mreturn[0m [0mself[0m[1;33m.[0m[0mrequest[0m[1;33m([0m[1;34m'POST'[0m[1;33m,[0m [0murl[0m[1;33m,[0m [0mdata[0m[1;33m=[0m[0mdata[0m[1;33m,[0m [0mjson[0m[1;33m=[0m[0mjson[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    591[0m [1;33m[0m[0m
[0;32m    592[0m     [1;32mdef[0m [0mput[0m[1;33m([0m[0mself[0m[1;33m,[0m [0murl[0m[1;33m,[0m [0mdata[0m[1;33m=[0m[1;32mNone[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\requests\sessions.py[0m in [0;36mrequest[1;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)[0m
[0;32m    526[0m             [0mhooks[0m[1;33m=[0m[0mhooks[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    527[0m         )
[1;32m--> 528[1;33m         [0mprep[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0mprepare_request[0m[1;33m([0m[0mreq[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    529[0m [1;33m[0m[0m
[0;32m    530[0m         [0mproxies[0m [1;33m=[0m [0mproxies[0m [1;32mor[0m [1;33m{[0m[1;33m}[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\requests\sessions.py[0m in [0;36mprepare_request[1;34m(self, request)[0m
[0;32m    454[0m [1;33m[0m[0m
[0;32m    455[0m         [0mp[0m [1;33m=[0m [0mPreparedRequest[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 456[1;33m         p.prepare(
[0m[0;32m    457[0m             [0mmethod[0m[1;33m=[0m[0mrequest[0m[1;33m.[0m[0mmethod[0m[1;33m.[0m[0mupper[0m[1;33m([0m[1;33m)[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    458[0m             [0murl[0m[1;33m=[0m[0mrequest[0m[1;33m.[0m[0murl[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\requests\models.py[0m in [0;36mprepare[1;34m(self, method, url, headers, files, data, params, auth, cookies, hooks, json)[0m
[0;32m    318[0m         [0mself[0m[1;33m.[0m[0mprepare_cookies[0m[1;33m([0m[0mcookies[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    319[0m         [0mself[0m[1;33m.[0m[0mprepare_body[0m[1;33m([0m[0mdata[0m[1;33m,[0m [0mfiles[0m[1;33m,[0m [0mjson[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 320[1;33m         [0mself[0m[1;33m.[0m[0mprepare_auth[0m[1;33m([0m[0mauth[0m[1;33m,[0m [0murl[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    321[0m [1;33m[0m[0m
[0;32m    322[0m         [1;31m# Note that prepare_auth must be last to enable authentication schemes[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\requests\models.py[0m in [0;36mprepare_auth[1;34m(self, auth, url)[0m
[0;32m    554[0m [1;33m[0m[0m
[0;32m    555[0m             [1;31m# Allow auth to make its changes.[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 556[1;33m             [0mr[0m [1;33m=[0m [0mauth[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    557[0m [1;33m[0m[0m
[0;32m    558[0m             [1;31m# Update self to reflect the auth changes.[0m[1;33m[0m[1;33m[0m[0m

[1;31mTypeError[0m: 'tuple' object is not callable
TypeError: 'tuple' object is not callable

